#/application.py
CAMERA_INDICES = (2, 1, 0)
FRAME_WIDTH = 600

#/preprocessing.py
MEDIAN_BLUR = 5
ADAPTIVE_BLOCK_SIZE = 11
ADAPTIVE_C = 2
FINAL_MEDIAN_KERNEL = 3

VERTICAL_CLOSE_KERNEL = (3, 11)
VERTICAL_CLOSE_ITERATIONS = 1

DILATION_KERNEL = (2, 2)
DILATION_ITERATIONS = 1

#/recognition.py
DIGIT_MIN_WIDTH = 5
DIGIT_MAX_WIDTH = 150
DIGIT_MIN_HEIGHT = 55
DIGIT_MAX_HEIGHT = 250

SEGMENT_WIDTH_RATIO = 0.25
SEGMENT_HEIGHT_RATIO = 0.15
MIDDLE_SEGMENT_RATIO = 0.05
ACTIVATION_RATIO = 0.30



#/stabilization.py
HISTORY_SIZE = 15
MINIMUM_VOTES = 5
SEARCHING_TEXT = "Buscando..."